server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/we_blog_db?serverTimezone=Asia/Shanghai
    username: root
    password: lf_MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      port: 6379
      host: localhost
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto # id的类型为自增
      table-prefix: tb_ # 表的前缀名为tb_
